//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Local_Trader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Local_Trader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11215R11rRf5bqQ749WUNx1GHVbTeeqvaX
        ///1121GMjp5VNW5kmt48ZRa6QaZJBZQCCAJC
        ///1121PqkhyQbAE4maScVzb3zSpzgiLj5caJ
        ///1121utV55FoYCoS4ndYRNwY8PznBq86k2J
        ///1122dAQa7z59EYUHT4H2QtEEvgZQKQjSRq
        ///1123ngtFNitBqwt2ssZ2rRiDdMFTtTPSuf
        ///112482E6WXTDJv8ybH24sPn2ZftDZASucc
        ///1124enrrjSe2HPTRahPYiCvGNAcotRMA2N
        ///1124niiCLUaZQgSD4TwKqkSEA4qCeTKbzL
        ///1126Cd8GYBHzVTU2xRV6Vx1kzCWJdtvuJN
        ///1127iafxoqL6tDghu9anZhvoWbaEm8N7s8
        ///1127QKeVSnBFCozekgGDL81b3i9pXT8iA7
        ///1127rUcwNATufMMrUwsSFF8Q1LD3n6ntNa
        ///1127xk2NFym7HCAw2XpgLFx3kxEchDCc5G
        ///112884UQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string vanityAddresses {
            get {
                return ResourceManager.GetString("vanityAddresses", resourceCulture);
            }
        }
    }
}
